name: example03
on: [push]
jobs:
  container-test-job:
    runs-on: self-hosted
    container:
      image: docker.io/rkalluru/learnk8s:rhel9-bare
    steps:
      - name: Just Hello
        run: echo Hello

