name: Storing and Sharing Data Example

on:
  workflow_dispatch:

jobs:
  create-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a sample text file
        run: |
          echo "This is a sample text file created during the workflow." > sample.txt

      - name: Upload the text file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: sample-text-file  # Artifact name (this will be used for downloading)
          path: sample.txt        # File to be uploaded

  use-artifact:
    runs-on: ubuntu-latest
    needs: create-artifact  # Ensure this job runs after the 'create-artifact' job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: sample-text-file  # Ensure this matches the artifact name used during upload

      - name: Read the content of the sample text file
        run: |
          cat sample-text-file/sample.txt  # The path will include the artifact folder name
