name: example11
on: [workflow_dispatch]
jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - run: touch new.txt
      - run: ls -l
  stage2:
    runs-on: ubuntu-latest
    steps:
      - run: ls -l



